### ISSUE TITLE
Graceful shutdown of the client library

### ISSUE THREAD

**Issue by satishramaswamy** [sshtools/maverick-synergy#12]
What is the best way to shutdown the client library when used in a web application ?
Will you be able to provide an API for that ?
Some threads are left running when the web application is redeployed in a container like tomcat.

I had to do the following

SshEngine.getDefaultInstance().shutdownNow(true, 2000);
Log.getDefaultContext().shutdown();  //this can potentially throw a null pointer exception as the DefaultLoggerContext.watcher can be null

I still have the following thread running

Name: SSHD-ACCEPT-1
State: RUNNABLE
Total blocked: 0  Total waited: 0
Stack trace:
java.base@15/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
java.base@15/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:357)
java.base@15/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:182)
java.base@15/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
   - locked sun.nio.ch.Util$2@7ee85529
   - locked sun.nio.ch.WindowsSelectorImpl@66affdba
java.base@15/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:141)
com.sshtools.synergy.nio.SelectorThread.run(SelectorThread.java:415)

**Comment by ludup** [comment]
The shutdown method of DefaultLoggingContext was added specifically for containers like tomcat that complain about thread leaks. 

I've added a shutdownAndExit method to SshEngine that performs the shutdown of the engine, and calls the shutdown on DefaultLoggingContext. And fixed the NPE also. 

It's not clear whether you are saying that even after those calls the thread you pasted into your issue was still present. Please confirm?

**Comment by satishramaswamy** [comment]
Sorry for not being clear, the thread was running even after those calls. 
It does not happen all the time though.

**Comment by ludup** [comment]
I would appreciate if you could let me know if this is still an issue with the latest RC5 and provide thread dump and logs to support it.

**Comment by ludup** [comment]
Unresponsive. Closing, if this is still an issue please provide logs and thread dump,
