### ISSUE TITLE
Certificate Signing with Extensions Are Ignored

### ISSUE THREAD

**Issue by iamgollum** [sshtools/maverick-synergy#14]
**Observation**

When CA signed user certificate generation is attempted with extensions, I notice that the produced signed certificate has no extensions. 

**Investigation**

The extensions are not being written and processed correctly. It also seems that key value extensions only handle key (flag) based.

In `OpenSshCertificate.java` extensions are read in assuming that it has no key value pairs:

```
for(String ext : extensions) {
	this.extensions.put(ext, "");
}
```

This will fail for my case where Github requires an extension that needs a value. In my code I have something like this for `ssh-keygen` process generation: `String.format("extension:%s=%s", key, value)`. 

In the `#sign()` the ByteArrayWriter (or some other writer) never writes the extensions so when `#decodeCertificate(reader)` is called we have:

```
tmp = new ByteArrayReader(reader.readBinaryString());
this.extensions = new HashMap<>();
this.extensionOrder = new ArrayList<>();
while (tmp.available() > 0) {
	String name = tmp.readString().trim();
	extensionOrder.add(name);
	extensions.put(name, tmp.readString());
}
tmp.close();
```

The extensions that had values in it are now removed from the state and tmp is empty at this stage since no extensions were written. Whats interesting with the above code is that this could work with key value pairs if they were written in the first place.

When the OpenSshCertificate is generated, the extension map is empty.

**Ask**

Can extensions be encoded correctly with the certificate?
Can extensions support key / value pairs ie. Github Ssh Certificates?

Update blog article with key value pair example: https://www.jadaptive.com/openssh-certificate-cheat-sheet/

Update API docs:
https://www.jadaptive.com/app/manpage/en/article/2895616

Consider creating a new overloaded method that takes in a Map of Extensions instead of a List<String> since you end up trying to convert it anyway in the code.

**Notes**

I would be happy to make time to work with the team to help code this if there is not enough staffing on the JAdaptive side to handle this.

I can also help contribute to the cheat sheet by providing a Github SSH Signing Example.

**Comment by ludup** [comment]
I have committed a fix to the encoding issues. Both extensions and critical options should now be encoded correctly during the sign operation.

I'd be happy to publish an example of signing for Github if you can provide one.

**Comment by iamgollum** [comment]
@ludup thank you so much!

Here is a Github Example of signing with a CA a users public ssh key for github:

```
 ssh-keygen -s [path to CA file] -I KEY-IDENTITY -V +52w -O **extension:login@github.ibm.com=ludup** ssh-key.pub
```

**Comment by iamgollum** [comment]
@ludup the `SshCertificateAuthority` also needs an api update to take in a Map<String,String> extensions.

**Comment by iamgollum** [comment]
@ludup the extensions show up now in the produced Ssh Certificate but as mentioned in my previous reply, the code does not handle the value aspects. I noticed you still maintain a List on the Authority component so the only way to do it is to provide key and value sequentially but that does not process because they become to key entries. If your able to fix the above I think this should be good to go.

**Comment by ludup** [comment]
Yes, I failed to complete the work on SshCertificateAuthority to add the ability to pass a Map of name/values. I will do so shortly.

**Comment by ludup** [comment]
SshCertificateAuthority now has Map<String,String> extensions parameter.

**Comment by iamgollum** [comment]
Thanks @ludup I think its fine now for this issue. (Going to see if I write this to a file in the correct format, I presume maverick has a utility for this as well)...

**Comment by iamgollum** [comment]
@ludup let me know when RC6 is released. Everything works on my end!

**Comment by ludup** [comment]
Pretty sure that was all in RC5 which has been released.

**Comment by iamgollum** [comment]
Thanks @ludup for the clarification as RC5 does work for the above!

**Comment by iamgollum** [comment]
@ludup I tested this with my Github Use case and I am getting a rejection.
Here is the difference in the certificates between the ssh-keygen vs. the maverick api:

`ssh-keygen`

```
        Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: RSA-CERT SHA256:JLm/c5O3ZbLd2/7pD8Z/PsHM8TiXJjx7jDHeJ4If1QA
        Signing CA: RSA SHA256:UpGjC+XHqiqmky+maxVXUrH3ek/+PS5K6ZjEWLRKOZU (using ssh-rsa)
        Key ID: "KEY-IDENTITY"
        Serial: 0
        Valid: from 2021-04-13T15:20:00 to 2021-07-12T15:21:40
        Principals: (none)
        Critical Options: (none)
        Extensions:
                permit-X11-forwarding
                permit-agent-forwarding
                permit-port-forwarding
                permit-pty
                permit-user-rc
                login@github.ibm.com UNKNOWN OPTION (len 16)
```

`maverick api`

```
       Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: RSA-CERT SHA256:JLm/c5O3ZbLd2/7pD8Z/PsHM8TiXJjx7jDHeJ4If1QA
        Signing CA: RSA SHA256:UpGjC+XHqiqmky+maxVXUrH3ek/+PS5K6ZjEWLRKOZU (using ssh-rsa)
        Key ID: "joe"
        Serial: 0
        Valid: from 2021-04-13T07:00:00 to 2021-07-12T07:00:00
        Principals:
                joe
        Critical Options: (none)
        Extensions:
                login@github.ibm.com UNKNOWN OPTION (len 10)
```

I will debug the extensions but curious what you maybe thinking here?

**Comment by iamgollum** [comment]
@ludup I tested this with my Github Use case and I am getting a rejection.
Here is the difference in the certificates between the ssh-keygen vs. the maverick api:

`ssh-keygen`

```
        Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: RSA-CERT SHA256:JLm/c5O3ZbLd2/7pD8Z/PsHM8TiXJjx7jDHeJ4If1QA
        Signing CA: RSA SHA256:UpGjC+XHqiqmky+maxVXUrH3ek/+PS5K6ZjEWLRKOZU (using ssh-rsa)
        Key ID: "KEY-IDENTITY"
        Serial: 0
        Valid: from 2021-04-13T15:20:00 to 2021-07-12T15:21:40
        Principals: (none)
        Critical Options: (none)
        Extensions:
                permit-X11-forwarding
                permit-agent-forwarding
                permit-port-forwarding
                permit-pty
                permit-user-rc
                login@github.ibm.com UNKNOWN OPTION (len 16)
```

`maverick api` default extensions were not accessible so I transferred your impl into my class (Github rejects it)

```
       Type: ssh-rsa-cert-v01@openssh.com user certificate
        Public key: RSA-CERT SHA256:JLm/c5O3ZbLd2/7pD8Z/PsHM8TiXJjx7jDHeJ4If1QA
        Signing CA: RSA SHA256:UpGjC+XHqiqmky+maxVXUrH3ek/+PS5K6ZjEWLRKOZU (using ssh-rsa)
        Key ID: "aaron"
        Serial: 0
        Valid: from 2021-04-13T07:00:00 to 2021-07-12T07:00:00
        Principals:
                aaron
        Critical Options: (none)
        Extensions:
                permit-agent-forwarding
                permit-port-forwarding
                login@github.ibm.com UNKNOWN OPTION (len 12)
                permit-pty
                permit-user-rc
                permit-x11-forwarding UNKNOWN OPTION (len 0)
```

I will debug the extensions but curious what you maybe thinking here?

**Comment by ludup** [comment]
I need to make some changes, when examining the spec in more detail for this I noticed a couple of issues, first, extensions need to be lexically ordered, although parsing with ssh-keygen does not like it when the custom extension is before the default set of extensions. That requires more investigation.

Second, the "string" value of the extension is not a plain string, but a binary string that could potentially be encoded with other complex objects. This is where the discrepancy in the length comes into play above because the "string" is encoded within another string. That's not really clear until you see a custom extension in the certificate and parse it.

Will resolve for RC6 and introduce some tests to back the changes up.

**Comment by iamgollum** [comment]
@ludup much appreciated. Just to clarify the scenario I went through. I used java stream to merge the extensions so it didn't preserve the order. I can easily pass in the extensions using the same order as ssh-keygen. For sshkeygen I only passed in the github extension as the default ones were added along with the one I provided. The user certificate api does not allow for such extensions so I use the lower level api that that method calls in which I added the default extensions from my end as the ones you have are protected.

**Comment by iamgollum** [comment]
@ludup checking in on the custom extension fix.

**Comment by ludup** [comment]
I've had to push this back to RC7 as it's quite an effort. But I will be starting this no later than next week.

**Comment by iamgollum** [comment]
Thank you so much @ludup

**Comment by ludup** [comment]
I've just committed a set of changes to OpenSSH certificate support to make it easier to work with extensions.

Extensions and Critical Options are now defined types that should now decode/encode correctly (subject to wider testing). 

You can now build a List of extensions/options using the Builder pattern. See Certificates with Extensions section of https://www.jadaptive.com/app/manpage/en/article/2895616

**Comment by iamgollum** [comment]
Thanks @ludup , I will give this a spin and update this thread accordingly if I make further progress.

**Comment by iamgollum** [comment]
@ludup the extension formats look good now however I encountered a different issue filed as a separate issue so you can close this issues out: #21
