### ISSUE TITLE
Per-Connection Logs not showing if user and ident filters are not provided

### ISSUE THREAD

**Issue by dandalf** [sshtools/maverick-synergy#15]
The documentation for enabling per-connection logging (https://www.jadaptive.com/app/manpage/en/article/1564950) suggests that the user and ident properties are optional filters to reduce the logs. However, the system is not producing any log files if I do not provide values for those properties.

The `isLoggingUser` and `isLoggingIdentifier` methods in ConnectionLoggingContext seem to have the bug in the first 4 lines of their code: 

```	
      private boolean isLoggingUser(Connection<?> con) {
			
		String v = getProperty(".user", "");
		if("".equals(v)) {         // <-- The property value defaults to the blank value so the returned value is false if a value is not provided
			return false;
		}
		Set<String> users = new HashSet<String>(Arrays.asList(v.split(",")));
		if(!Objects.isNull(con.getUsername())) {
			return users.contains(con.getUsername());
		} else {
			return users.isEmpty();
		}
	}
```

**Comment by ludup** [comment]
Thanks, I've just committed a fix for this and it should now generate per-connection logs without an ident or user value set.

**Comment by dandalf** [comment]
This is working now, thank you!
