### ISSUE TITLE
Terminated executor is reused

### ISSUE THREAD

**Issue by dandalf** [sshtools/maverick-synergy#16]
The static executor field on SshContext can be shutdown and then reused by another SshClient, resulting in an exception when trying to connect to the server:

`    java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1e3a0815[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2fdf07c1[Wrapped task = com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask@6049443b]] rejected from java.util.concurrent.ThreadPoolExecutor@5785f3a0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2965]`

As seen in the exception, the ThreadPoolExecutor has a Terminated status. 

As a workaround, I am using reflection to set the executor to null so a new one is created when necessary. I think the SshContext.shutdown function should explicitly set the executor to null so the terminated executor is not reused.

**Comment by ludup** [comment]
Thanks, this will be fixed in 3.0.0-RC6 which will be pushed out later today.
