### ISSUE TITLE
Problem configuring viritual file system

### ISSUE THREAD

**Issue by tim-terry-otm** [sshtools/maverick-synergy#2]
Hi,

When trying to configure the virtual file system on the server from the docs here:
https://www.jadaptive.com/app/manpage/en/article/1587734

```
server.setFileFactory(new VirtualFileFactory(new VFSFileFactory()));
```

When using the latest 3.0.0-SNAPSHOT version a FileFactory is expected instead of an AbstractFileFactory. What would be the correct way to configure the server with a virtualFileFactory?

Thanks

Tim

**Comment by ludup** [comment]
Thanks for getting in touch.

Sorry about the confusion, I committed some changes last week that changed a few things and have not updated the documentation yet. 

Below is how you configure VirtualFileFactory

	server.setFileFactory(new FileFactory() {
	  @Override
	  public AbstractFileFactory<?> getFileFactory(SshConnection con) 
			throws IOException, PermissionDeniedException {
	   return new VirtualFileFactory(
			new VirtualMountTemplate("/", "tmp://", 
			new VFSFileFactory(), true));
	  }
	});

**Comment by tim-terry-otm** [comment]
Thanks!
