### ISSUE TITLE
Extra slash in file actual path resolution

### ISSUE THREAD

**Issue by dandalf** [sshtools/maverick-synergy#20]
In the com.sshtools.common.files.vfs.VirtualMappedFile#toActualPath ( https://github.com/sshtools/maverick-synergy/blob/984fe9bf734a68f75447ae1ec129a200c3308dac/maverick-virtual-filesystem/src/main/java/com/sshtools/common/files/vfs/VirtualMappedFile.java#L218 ) it is possible for a virtual path to get an extra slash.

To replicate this, create a virtual mount that has a mount with a leading slash and no trailing slash (e.g., /readonly on ram://root/read ). Then query a virtual path for that mount (e.g., /readonly/file.txt).

The toActualPath method will execute line 218:
```
str = FileUtils.addTrailingSlash(parentMount.getRoot())
					+ virtualPath.substring(parentMount.getMount().length());
```

The virtualPath substring call will result in `/file.txt`, which is appended to the root with trailing slash ending up with an actual path of: `ram://root/read//file.txt` which has a double slash.

Since VirutalMountTemplate strips the trailing slashes, I am not sure how to work around this problem.

**Comment by dandalf** [comment]
I have worked around this problem by normalizing the path before getting the remote resource like so:
`normalizedUri = URI.create(absolutePath).normalize();`

**Comment by ludup** [comment]
I committed a fix to ensure the child element was chopped at the correct length.

**Comment by dandalf** [comment]
Thank you!
