### ISSUE TITLE
Double shutdown results n OutOfMemoryError

### ISSUE THREAD

**Issue by dandalf** [sshtools/maverick-synergy#24]
The library can create an infinite loop if the ssh server is shutdown twice due to the shutdown method using the `getExecutorService()` method which will create a new executor service and add a new shutdown hook after the server has been shutdown once. 

resolved by #23

**Comment by dandalf** [comment]
This pull request has a possible solution: #23

**Comment by ludup** [comment]
Thanks, the pull request has now been merged.
