### ISSUE TITLE
Add kex negotiation connection timeout to fix DoS attack vector

### ISSUE THREAD

**Issue by dandalf** [sshtools/maverick-synergy#25]
When running a protocol fuzzer against the maverick library, we found an issue where the server will keep a connection open indefinitely during the DH group exchange negotiation process. An attacker could use this behavior to exhaust the server's connections and deny service to users. This file has the trace log files for the connection that show the server is waiting in a state of 'Transport protocol is expecting another packet':
[2021-06-09-16-03-58-143__1202fbee-d9aa-4a20-86fd-9c98ae9c2267_.log](https://github.com/sshtools/maverick-synergy/files/6626937/2021-06-09-16-03-58-143__1202fbee-d9aa-4a20-86fd-9c98ae9c2267_.log)

The code that disregards the fuzzed packet and decides to wait forever seems to be here:
https://github.com/sshtools/maverick-synergy/blob/5afe567a542089951ef29d08bec3599e7930422d/maverick-synergy-server/src/main/java/com/sshtools/server/components/jce/DiffieHellmanGroupExchangeSha1JCE.java#L163-L167 

Ideally, the connection would close after a configurable amount of time when it is left in this state. If that is not feasible, can you think of a way my application code can monitor this process to shut down connection when appropriate?

Thank you in advance.

**Comment by ludup** [comment]
I have fixed this in my most recent commit. 

There were two issues. We already had a timeout mechanism, but it was not being engaged at the transport level, so setIdleConnectionTimeoutSeconds was not actually working as designed. setIdleAuthenticationTimeoutSeconds which deals with timeouts prior to a successful authentication was working, but only after the AuthenticationProtocol was started, which does not happen until after key exchange has completed.

So there are two fixes committed. 

1. Engage the transport protocols idle timeout mechanism to fix general timeouts.
2. Add handling to transport protocol for negotiating protocol and key exchange states, using the setIdleAuthenticationTimeoutSeconds value as the threshold.

**Comment by dandalf** [comment]
Works like a charm, thank you!
