### ISSUE TITLE
SFTP subsystem hangs on OpenSSH command line client 'exit' command

### ISSUE THREAD

**Issue by thorntech** [sshtools/maverick-synergy#26]
When connecting to SFTP using the OpenSSH command line client, the client hangs indefinitely after issuing the "exit" command. This affects many production scripts that automate file transfers. 

```
Jeffs-MacBook-Pro:myfiles jthorn$ ssh -V
OpenSSH_7.9p1, LibreSSL 2.7.3
Jeffs-MacBook-Pro:myfiles jthorn$ sftp jeff@xxx.xxx.xxx.xxx
Connected to jeff@xxx.xxx.xxx.xxx.
sftp> exit
```
The client never returns after the exit command.

**Comment by ludup** [comment]
A fix for this has been committed and will be available in the maven repositories shortly in RC8-SNAPSHOT.

**Comment by dandalf** [comment]
The fix works well! Thanks @ludup
