### ISSUE TITLE
Listing duplicate folders

### ISSUE THREAD

**Issue by dandalf** [sshtools/maverick-synergy#27]
I am experiencing an issue where listing the contents of the directory is producing multiple of the same folder. I tracked the problem to line 94 of the VirtualMappedFile class. The getChildren method produces duplicate folders when there are mounts to subfolders. For example, I have mounts defined at these folders:

1. /
2. /folder_a
3. /folder_b
4. /folder_b/subfolder_a
5. /folder_b/subfolder_b

When running getChildren from "/", the result shows 4 files:
folder_a
folder_b
folder_b
folder_b

I would expect the result to contain just folder_a and folder_b.

The getChildren method in VirtualMountFile has similar code producing the duplicately named files as well starting on line 99.

**Comment by ludup** [comment]
Confirmed. 

There will be a 3.0.2 version with a fix in the next few days.

**Comment by ludup** [comment]
3.0.3-Final is now available.

The version number is different because we found some client issues that required immediate updates.

**Comment by dandalf** [comment]
Thank you @ludup !
