### ISSUE TITLE
Is there a way to `ls` for a file directly and not have to be a directory?

### ISSUE THREAD

**Issue by jamoros** [sshtools/maverick-synergy#35]
I'm using the `ls` command in the `SftpClientTask` but I get an exception that it is not a directory. Which is fine, as I was currently checking if its a file or not. What is the alternative to check for a file if it exists?

Thank you!!

**Comment by ludup** [comment]
That is what the stat method is for. It returns the attributes of the file so you can check its type or the isDirectory method of SftpFileAttributes.

**Comment by jamoros** [comment]
Thank you for your response, I will be trying that in my implementation this week.
