### ISSUE TITLE
SshException: Minimum DH p value not provided [1024]

### ISSUE THREAD

**Issue by jamoros** [sshtools/maverick-synergy#36]
Greetings!

I ran into an issue and I am not sure how to go about it or what I need to do on my end to fix it. Below is some of the log, if you want I can post the complete DEBUG log. I looked at the source and see that it's a less than but the value of p is actually equal to, is there a way to go around that? I may be completely off base since I am still learning.

[     pool-1-thread-1]  DEBUG - Lang: 
[     pool-1-thread-1]  DEBUG - First Packet Follows: false
[     pool-1-thread-1]  DEBUG - Local Key Exchanges: diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,rsa2048-sha256,diffie-hellman-group14-sha1
[     pool-1-thread-1]  DEBUG - Local Public Keys: ecdsa-sha2-nistp256,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ssh-rsa,ssh-rsa-cert-v01@openssh.com
[     pool-1-thread-1]  DEBUG - Local Ciphers CS: aes256-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes192-ctr,aes128-ctr,3des-ctr,aes256-cbc,3des-cbc,aes128-cbc
[     pool-1-thread-1]  DEBUG - Local Ciphers SC: aes256-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes192-ctr,aes128-ctr,3des-ctr,aes256-cbc,3des-cbc,aes128-cbc
[     pool-1-thread-1]  DEBUG - Local Macs SC: hmac-sha2-512-etm@openssh.com,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96
[     pool-1-thread-1]  DEBUG - Local Macs CS: hmac-sha2-512-etm@openssh.com,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96
[     pool-1-thread-1]  DEBUG - Local Compression CS: none
[     pool-1-thread-1]  DEBUG - Local Compression SC: none
[     pool-1-thread-1]  DEBUG - Firing EVENT_KEY_EXCHANGE_INIT success=true
[     pool-1-thread-1]  DEBUG - Lang: 
[     pool-1-thread-1]  DEBUG - First Packet Follows: false
[     pool-1-thread-1]  DEBUG - Local Key Exchanges: diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,curve25519-sha256,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,rsa2048-sha256,diffie-hellman-group14-sha1
[     pool-1-thread-1]  DEBUG - Local Public Keys: ecdsa-sha2-nistp256,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ssh-rsa,ssh-rsa-cert-v01@openssh.com
[     pool-1-thread-1]  DEBUG - Local Ciphers CS: aes256-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes192-ctr,aes128-ctr,3des-ctr,aes256-cbc,3des-cbc,aes128-cbc
[     pool-1-thread-1]  DEBUG - Local Ciphers SC: aes256-ctr,aes256-gcm@openssh.com,aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes192-ctr,aes128-ctr,3des-ctr,aes256-cbc,3des-cbc,aes128-cbc
[     pool-1-thread-1]  DEBUG - Local Macs CS: hmac-sha2-512-etm@openssh.com,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96
[     pool-1-thread-1]  DEBUG - Local Macs SC: hmac-sha2-512-etm@openssh.com,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512,hmac-sha2-512-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha256@ssh.com,hmac-sha2-256,hmac-sha2-256-96,hmac-sha1-etm@openssh.com,hmac-sha1,hmac-sha1-96
[     pool-1-thread-1]  DEBUG - Local Compression CS: none
[     pool-1-thread-1]  DEBUG - Local Compression SC: none
[     pool-1-thread-1]  DEBUG - Firing EVENT_KEY_EXCHANGE_INIT success=true
[     pool-1-thread-1]   INFO - Using BC for DH; prime range is 1024 to 8192 bits
[     pool-1-thread-1]  DEBUG - Negotiated Key Exchange: diffie-hellman-group-exchange-sha256
[     pool-1-thread-1]  DEBUG - Negotiated Public Key: ssh-rsa
[     pool-1-thread-1]  DEBUG - Negotiated Cipher CS: aes256-ctr
[     pool-1-thread-1]  DEBUG - Negotiated Cipher SC: aes256-ctr
[     pool-1-thread-1]  DEBUG - Negotiated Mac CS: hmac-sha1
[     pool-1-thread-1]  DEBUG - Negotiated Mac SC: hmac-sha1
[     pool-1-thread-1]  DEBUG - Negotiated Compression CS: none
[     pool-1-thread-1]  DEBUG - Negotiated Compression SC: none
[     pool-1-thread-1]  DEBUG - Minimum DH prime size is 2048
[     pool-1-thread-1]  DEBUG - Preferred DH prime size is 2048
[     pool-1-thread-1]  DEBUG - Maximum DH prime size is 8192
[     pool-1-thread-1]  DEBUG - Sent SSH_MSG_KEY_DH_GEX_REQUEST
com.sshtools.common.ssh.SshException: Minimum DH p value not provided [1024]
                at com.sshtools.client.components.DiffieHellmanGroupExchange.exchangeGroup(DiffieHellmanGroupExchange.java:270)
                at com.sshtools.client.components.DiffieHellmanGroupExchange.processMessage(DiffieHellmanGroupExchange.java:405)
                at com.sshtools.synergy.ssh.TransportProtocol.processMessage(TransportProtocol.java:1992)
                at com.sshtools.synergy.ssh.TransportProtocol.processBinaryPackets(TransportProtocol.java:627)
                at com.sshtools.synergy.ssh.TransportProtocol.onSocketRead(TransportProtocol.java:457)
                at com.sshtools.client.TransportProtocolClient.onSocketRead(TransportProtocolClient.java:132)
                at com.sshtools.synergy.nio.SocketConnection.processReadEvent(SocketConnection.java:294)
                at com.sshtools.synergy.nio.SshEngine$SocketReadWriteTask.doTask(SshEngine.java:675)
                at com.sshtools.common.ssh.ConnectionAwareTask.run(ConnectionAwareTask.java:45)
                at com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask.executeAllTasks(ExecutorOperationSupport.java:128)[     pool-1-thread-1]   INFO - Using BC for DH; prime range is 1024 to 8192 bits
[     pool-1-thread-1]  DEBUG - Negotiated Key Exchange: diffie-hellman-group-exchange-sha256
[     pool-1-thread-1]  DEBUG - Negotiated Public Key: ssh-rsa
[     pool-1-thread-1]  DEBUG - Negotiated Cipher CS: aes256-ctr
[     pool-1-thread-1]  DEBUG - Negotiated Cipher SC: aes256-ctr
[     pool-1-thread-1]  DEBUG - Negotiated Mac CS: hmac-sha1
[     pool-1-thread-1]  DEBUG - Negotiated Mac SC: hmac-sha1
[     pool-1-thread-1]  DEBUG - Negotiated Compression CS: none
[     pool-1-thread-1]  DEBUG - Negotiated Compression SC: none
[     pool-1-thread-1]  DEBUG - Minimum DH prime size is 2048
[     pool-1-thread-1]  DEBUG - Preferred DH prime size is 2048
[     pool-1-thread-1]  DEBUG - Maximum DH prime size is 8192
[     pool-1-thread-1]  DEBUG - Sent SSH_MSG_KEY_DH_GEX_REQUEST
com.sshtools.common.ssh.SshException: Minimum DH p value not provided [1024]
                at com.sshtools.client.components.DiffieHellmanGroupExchange.exchangeGroup(DiffieHellmanGroupExchange.java:270)
                at com.sshtools.client.components.DiffieHellmanGroupExchange.processMessage(DiffieHellmanGroupExchange.java:405)
                at com.sshtools.synergy.ssh.TransportProtocol.processMessage(TransportProtocol.java:1992)
                at com.sshtools.synergy.ssh.TransportProtocol.processBinaryPackets(TransportProtocol.java:627)
                at com.sshtools.synergy.ssh.TransportProtocol.onSocketRead(TransportProtocol.java:457)
                at com.sshtools.client.TransportProtocolClient.onSocketRead(TransportProtocolClient.java:132)
                at com.sshtools.synergy.nio.SocketConnection.processReadEvent(SocketConnection.java:294)
                at com.sshtools.synergy.nio.SshEngine$SocketReadWriteTask.doTask(SshEngine.java:675)
                at com.sshtools.common.ssh.ConnectionAwareTask.run(ConnectionAwareTask.java:45)
                at com.sshtools.common.ssh.ExecutorOperationSupport$OperationTask.executeAllTasks(ExecutorOperationSupport.java:128)

I'd like to say thanks for this awesome library! It's solved so many issues for us and I am learning more about SSH connectivity. 

Any help would be greatly appreciated. Thank you!

**Comment by jamoros** [comment]
I just did some more investigating and the max value is actually 2048 but the value of p.bitLength is 1024. I am not sure what sets the p.bitLength value and how we can modify it so that I can pass this part of the key exchange. Any help would be very appreciated. Thanks.

**Comment by jamoros** [comment]
Ok after more searching I found that this works

`context.setMinDHGroupExchangeKeySize(1024);`

However, is this bad by design? Is there a better way to be able to go about this? Thanks again!

**Comment by ludup** [comment]
This appears to be a bad configuration in the software you are connecting to. We are requesting a minimum p-value of 2048 bits, but it appears the remote side wants it to be 1024 or does not have a 2048 bit key to supply. 

1024 is not that secure which is why our default is higher. As you did not include the beginning of the log output I can't see what flavour of SSH the remote side is. If you could let us know I'd appreciate it.

**Comment by jamoros** [comment]
Here's the rest of the log. Thank you for the informative response. Unfortunately it's out of our hands, you can close this ticket if you wish unless you want some more info from me I'll happy include it.

13 Jan 2022 17:20:19,959 [                main]   INFO - Console logging enabled
13 Jan 2022 17:20:19,983 [                main]   INFO - Product version: 3.0.6
13 Jan 2022 17:20:19,984 [                main]   INFO - OS: Linux amd64
13 Jan 2022 17:20:19,984 [                main]   INFO - Configuring SSH engine
13 Jan 2022 17:20:19,985 [                main]   INFO - Configuration complete
13 Jan 2022 17:20:20,018 [                main]   INFO - Configuring DH support with Bouncycastle BC provider
13 Jan 2022 17:20:20,018 [                main]   INFO - Initializing SSH2 server->client ciphers
13 Jan 2022 17:20:20,025 [                main]  DEBUG -    aes128-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,026 [                main]  DEBUG -    aes192-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,027 [                main]  DEBUG -    aes256-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,033 [                main]  DEBUG -    3des-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,036 [                main]  DEBUG -    aes128-gcm@openssh.com will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,038 [                main]  DEBUG -    aes256-gcm@openssh.com will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,038 [                main]   INFO - Initializing SSH2 client->server ciphers
13 Jan 2022 17:20:20,039 [                main]  DEBUG -    aes128-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,039 [                main]  DEBUG -    aes192-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,040 [                main]  DEBUG -    aes256-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,040 [                main]  DEBUG -    3des-ctr will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,041 [                main]  DEBUG -    aes128-gcm@openssh.com will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,042 [                main]  DEBUG -    aes256-gcm@openssh.com will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,042 [                main]   INFO - Initializing SSH2 server->client HMACs
13 Jan 2022 17:20:20,045 [                main]  DEBUG -    hmac-sha256 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,046 [                main]  DEBUG -    hmac-sha2-256-96 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,047 [                main]  DEBUG -    hmac-sha512 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,048 [                main]  DEBUG -    hmac-sha2-512-96 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,049 [                main]  DEBUG -    hmac-sha1 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,050 [                main]  DEBUG -    hmac-sha1-96 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,050 [                main]   INFO - Initializing SSH2 client->server HMACs
13 Jan 2022 17:20:20,050 [                main]  DEBUG -    hmac-sha256 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,050 [                main]  DEBUG -    hmac-sha2-256-96 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,050 [                main]  DEBUG -    hmac-sha512 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,050 [                main]  DEBUG -    hmac-sha2-512-96 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,051 [                main]  DEBUG -    hmac-sha1 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,051 [                main]  DEBUG -    hmac-sha1-96 will be supported using JCE Provider SunJCE
13 Jan 2022 17:20:20,052 [                main]   INFO - Initializing public keys
13 Jan 2022 17:20:20,062 [                main]  DEBUG -    ssh-ed25519 will not be supported: no such algorithm: Ed25519 for provider BC
13 Jan 2022 17:20:20,065 [                main]  DEBUG -    rsa-sha2-256 will be supported using JCE Provider SunRsaSign
13 Jan 2022 17:20:20,066 [                main]  DEBUG -    rsa-sha2-512 will be supported using JCE Provider SunRsaSign
13 Jan 2022 17:20:20,068 [                main]  DEBUG -    ecdsa-sha2-nistp256 will be supported using JCE Provider BC
13 Jan 2022 17:20:20,069 [                main]  DEBUG -    ecdsa-sha2-nistp384 will be supported using JCE Provider BC
13 Jan 2022 17:20:20,070 [                main]  DEBUG -    ecdsa-sha2-nistp521 will be supported using JCE Provider BC
13 Jan 2022 17:20:20,072 [                main]  DEBUG -    ssh-rsa-cert-v01@openssh.com will be supported using JCE Provider SunRsaSign
13 Jan 2022 17:20:20,074 [                main]  DEBUG -    ecdsa-sha2-nistp256-cert-v01@openssh.com will be supported using JCE Provider BC
13 Jan 2022 17:20:20,074 [                main]  DEBUG -    ecdsa-sha2-nistp384-cert-v01@openssh.com will be supported using JCE Provider BC
13 Jan 2022 17:20:20,075 [                main]  DEBUG -    ecdsa-sha2-nistp521-cert-v01@openssh.com will be supported using JCE Provider BC
13 Jan 2022 17:20:20,075 [                main]  DEBUG -    ssh-ed25519-cert-v01@openssh.com will not be supported: no such algorithm: Ed25519 for provider BC
13 Jan 2022 17:20:20,076 [                main]  DEBUG -    ssh-rsa will be supported using JCE Provider SunRsaSign
13 Jan 2022 17:20:20,077 [                main]  DEBUG -    ssh-dss will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,077 [                main]   INFO - Initializing digests
13 Jan 2022 17:20:20,078 [                main]  DEBUG -    MD5 will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,079 [                main]  DEBUG -    SHA-1 will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,079 [                main]  DEBUG -    SHA1 will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,079 [                main]  DEBUG -    SHA-256 will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,080 [                main]  DEBUG -    SHA-384 will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,080 [                main]  DEBUG -    SHA-512 will be supported using JCE Provider SUN
13 Jan 2022 17:20:20,081 [                main]   INFO - Initializing Secure Random Number Generator
13 Jan 2022 17:20:20,082 [                main]   INFO - Initializing client key exchanges
13 Jan 2022 17:20:20,091 [                main]  DEBUG -    curve25519-sha256 (client) will be supported using JCE Provider 
13 Jan 2022 17:20:20,095 [                main]  DEBUG -    curve25519-sha256@libssh.org (client) will be supported using JCE Provider 
13 Jan 2022 17:20:20,479 [                main]  DEBUG -    diffie-hellman-group-exchange-sha256 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:20,520 [                main]  DEBUG -    diffie-hellman-group14-sha256 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:20,627 [                main]  DEBUG -    diffie-hellman-group15-sha512 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:20,873 [                main]  DEBUG -    diffie-hellman-group16-sha512 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:21,617 [                main]  DEBUG -    diffie-hellman-group17-sha512 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:23,332 [                main]  DEBUG -    diffie-hellman-group18-sha512 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:23,368 [                main]  DEBUG -    diffie-hellman-group14-sha1 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:23,947 [                main]  DEBUG -    ecdh-sha2-nistp256 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:23,982 [                main]  DEBUG -    ecdh-sha2-nistp384 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:24,022 [                main]  DEBUG -    ecdh-sha2-nistp521 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:24,045 [                main]  DEBUG -    rsa2048-sha256 (client) will be supported using JCE Provider BC
13 Jan 2022 17:20:24,239 [     SSHD-TRANSFER-1]   INFO - Connnection created sft.statestreet.com/192.250.167.3:2222 on interface /10.0.2.15:44868
13 Jan 2022 17:20:24,241 [     SSHD-TRANSFER-1]  DEBUG - There is now 1 active connections on client connection manager
13 Jan 2022 17:20:24,245 [     SSHD-TRANSFER-1]  DEBUG - Firing EVENT_CONNECTED success=true
13 Jan 2022 17:20:24,274 [     pool-1-thread-1]  DEBUG - Sent local identification string SSH-2.0-MaverickSynergy
13 Jan 2022 17:20:24,297 [     pool-1-thread-1]   INFO - Connnection /10.0.2.15:44868 identifies itself as SSH-2.0-SSHD
13 Jan 2022 17:20:24,297 [     pool-1-thread-1]  DEBUG - Remote client version OK
13 Jan 2022 17:20:24,297 [     pool-1-thread-1]  DEBUG - Firing EVENT_NEGOTIATED_PROTOCOL success=true
13 Jan 2022 17:20:24,310 [     pool-1-thread-1]  DEBUG - Posting SSH_MSG_KEX_INIT
13 Jan 2022 17:20:24,311 [     pool-1-thread-1]  DEBUG - Sent SSH_MSG_KEX_INIT
13 Jan 2022 17:20:24,333 [     pool-1-thread-1]  DEBUG - Received SSH_MSG_KEX_INIT
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Key Exchanges: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Public Keys: ssh-rsa
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Ciphers CS: aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc,aes128-ctr,aes192-ctr,aes256-ctr
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Ciphers SC: aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc,aes128-ctr,aes192-ctr,aes256-ctr
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Macs CS: hmac-sha1,hmac-sha1-96
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Macs SC: hmac-sha1,hmac-sha1-96
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Compression CS: none,zlib
13 Jan 2022 17:20:24,334 [     pool-1-thread-1]  DEBUG - Remote Compression SC: none,zlib

**Comment by ludup** [comment]
The server identifies with SSH-2.0-SSHD do you know what server type that is? What's the real name of the software you are connecting to? Just helps to know this in case it comes up again.

**Comment by jamoros** [comment]
Unfortunately I currently do not have a contact to the connection, I'll see if I can get something soon. However I grabbed this info via WinScp. Hopefully this is somewhat helpful.

File transfer protocol = SFTP-3
Cryptographic protocol = SSH-2
SSH implementation = SSHD
Encryption algorithm = AES-256 SDCTR (AES-NI accelerated)
Compression = No
------------------------------------------------------------
Server host key fingerprints
SHA-256 = ssh-rsa 2048 
MD5 = ssh-rsa 2048 
------------------------------------------------------------
Can change permissions = Yes
Can change owner/group = Yes
Can execute arbitrary command = No
Can create symbolic/hard link = Yes/No
Can lookup user groups = No
Can duplicate remote files = No
Can check available space = No
Can calculate file checksum = No
Native text (ASCII) mode transfers = No
------------------------------------------------------------
Additional information
The server supports these SFTP extensions:
  newline@vandyke.com="\n"

**Comment by ludup** [comment]
Appreciate the info.
