### ISSUE TITLE
SshClient not honoring timeout

### ISSUE THREAD

**Issue by fritzfranzke** [sshtools/maverick-synergy#39]
Hi guys, I am running into an issue when trying to gracefully handle an SSH server being unreachable. When I initialize the client as follows

```
try (SshClient ssh = new SshClient(hostname, port, username, 5_000L, password.toCharArray())) {
    ...
} catch (IOException | SshException e) {
    log.error("Failed to connect: {}", e.getMessage());
}
```

I would expect the `catch` clause to fire if no connection can be established within 5 seconds. However, this is not the case. What happens when the timeout has elapsed?

Thanks!

**Comment by fritzfranzke** [comment]
That would be `maverick-synergy-client` version `3.0.6`. I trust this is the latest one?

**Comment by ludup** [comment]
Yes, 3.0.6 is the latest release of the open-source version, the proxy support is in the develop branch currently so that will not be the cause. I'll investigate it further and get back to you.

**Comment by ludup** [comment]
I have been trying to reproduce this without any success. The connect timeout is not using the standard socket mechanism as the connect is done asynchronously. So it's waiting on a future object that gets set when the connection is completed. When I set it to a very low figure and connect to a real server; if the server fails to connect in that time (something like 50ms) it's throwing the exception.

```
protected void doConnect(String hostname, int port, String username, SshClientContext sshContext, long connectTimeout) throws SshException, IOException {
	configure(sshContext);
	ConnectRequestFuture future = sshContext.getEngine().connect(hostname, port, sshContext);
	future.waitFor(connectTimeout);
	if(!future.isSuccess()) {
		throw new IOException(String.format("Failed to connect to %s:%d", hostname, port)); 
        }
        ...
}
```
Can you reproduce and grab and share some logs so I can compare them?

Also, when you say unreachable, it's not returning connection refused on that port? I guess that may be OS/Environment dependent.

**Comment by fritzfranzke** [comment]
Hi, sorry for the late reply. I tried replicating the issue but wasn't able to do so. I am guessing that the circuitbreaker I was using may have interfered and thrown misleading exceptions. I hope this didn't waste too much of your time. Thanks for investigating and the awesome work :)
