### ISSUE TITLE
Use API to sign client public certificate with CA

### ISSUE THREAD

**Issue by execretor** [sshtools/maverick-synergy#4]
Here (https://www.jadaptive.com/app/manpage/en/article/1579899) documentation says that using OpenSSH Certificate Authenticator I can configure the SSH server to accept CA-signed public certificates.

I know that using ssh-keygen utility I can sign client public certificate with server private key, but how can I do this operation with maverick API?

Best regards,
Lorenzo.

**Comment by ludup** [comment]
Hi Lorenzo,

Currently, it's not possible to sign as a CA. You have to use ssh-keygen. 

This is a feature I was planning on implementing soon so let's keep this issue open and I'll update it when it becomes available.

**Comment by execretor** [comment]
Do you have a plan for the release?

**Comment by ludup** [comment]
There is no schedule yet

**Comment by ludup** [comment]
This has been committed and should now be available in the latest SNAPSHOT version.

Generating User Certificates
https://www.jadaptive.com/app/manpage/agent/article/2895616

Generating Host Certificates
https://www.jadaptive.com/app/manpage/agent/article/2895831

**Comment by iamgollum** [comment]
@ludup is their plans to support for certificate extensions? 
Example use case using a CA to sign a ssh public key for github
