### ISSUE TITLE
Some noob build issues

### ISSUE THREAD

**Issue by MushyMiddle** [sshtools/maverick-synergy#5]
Hi.  We're looking at replacing our current, mature SSH implementation based on Jsch with Maverick Synergy, and so far, it looks very promising.  (Jsch is lacking in recent cipher support).

I look forward to integrating with Maverick Synergy, and appreciate all of the hard work that's obviously gone into it.

That said, I ran into a few issues trying to build from source, the initial objective being to get complete Javadocs for the API, since they don't seem to be online.  Admittedly, I'm a Maven novice (we mostly use Ant), so some of this may just be my learning curve - take this with that grain of salt.

1. In the main pom.xml, Maven (3.6.0) now seems to want the URL in the scm element to be prefixed by "scm:git:...", e.g.:

        <scm>
                <url>https://github.com/sshtools/maverick-synergy/</url>
                <connection>scm:git:https://github.com/sshtools/maverick-synergy.git</connection>
        </scm>

2. It seems the Java 8 compiler *must* be used, not just Java 8 compatibility.  Post-Java 8, Thread.destroy() has been removed from java.lang.Thread.  Because Maven wants to bring in Java 11 on Ubuntu 18.04, I think the Java 11 compiler had issues with use of Thread.destroy().  The fix was to force the Java 8 compiler to be used instead of Java 11 in pom.xml:

                        <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.1</version>
                                <configuration>
                                        <source>1.8</source>
                                        <target>1.8</target>
                                        <executable>/usr/lib/jvm/java-8-openjdk-amd64/bin/javac</executable>
                                        <compilerVersion>1.8</compilerVersion>
                                        <fork>true</fork>
                                </configuration>
                        </plugin>

...though I think this can be avoided by setting JAVA_HOME to point to the Java 8 JDK.  To be clear, I didn't want Java 11, but Maven did (via apt).

3. In maverick-synergy-fuse-drive/pom.xml, the repository URL has to be https://... these days, apparently, not http://...

        <repositories>
                <repository>
                        <id>central</id>
                        <name>bintray</name>
                        <url>https://jcenter.bintray.com</url>
                </repository>
        </repositories>

...symptom was a 403/Forbidden when trying to download dependencies.

4.  Some tests would fail, so I had to specify -DskipTests.  Perhaps some other set up is needed in order to run tests?  It looks like some paths may be hard-coded in some of the tests (/home/user/test/...).

5.  I also had to disable jar signing (more set up needed?) and license checking (-Dlicense.skip=true).

6.  It would be nice to have aggregated Javadocs.  As mentioned, my goal was to get a complete set of Javadocs (aggregated).  This proved to be difficult, as pom.xml isn't really set up to support the site lifecycle needed for this.  I was finally able to get what I wanted, more or less, by hacking-in maven-site-plugin, though that wasn't 100% successful - I had to do "mvn javadoc:aggregate-jar" to get Javadocs aggregated.  It would be nice to have complete Javadocs if needed, vs. having to dig around individual projects.  To be clear, Javadocs were generated for all projects - just not aggregated to the site target.

Anyway, thanks again for all the hard work.  Hope this helps the next person getting started from scratch.

**Comment by ludup** [comment]
Thank you for the info.

I've fixed the pom issues; the assembly was already attempting to build aggregated javadocs but it was failing because of the packaging type of the pom. This is now fixed.

I've adjusted our build to upload the aggregated javadocs to [here](https://maverick-synergy-javadocs.s3.eu-west-1.amazonaws.com/index.html)

Signing is now performed using a Maven profile so it won't apply unless specifically invoked. This is only required for uploading to Maven Central. 

Tests are now fixed and license headers configured correctly. 

Thanks again for your input, much appreciated.

**Comment by ludup** [comment]
I should make a comment on the Javadocs, they have not had much work so may be out of date in many areas. As we move to a final release version I will get around to get these updated. Our main documentation is at https://www.jadaptive.com/app/manpage/en/category/1559751 and if you cannot find a specific example, please ask, it will be easy for me to update the documentation with specific examples requested.

**Comment by MushyMiddle** [comment]
Thanks for the quick work - much appreciated.
