### ISSUE TITLE
SSHClient -Failed to negotiate a transport component

### ISSUE THREAD

**Issue by radhesh-kunnath** [sshtools/maverick-synergy#57]
Hi guys, I'm trying to ssh into a cluster node by using sshclient
Ex: SshClient ssh = new SshClient(hostname, port, username, password.toCharArray()

Exception:
java.io.IOException: Failed to negotiate a transport component from {} and {}
java.io.IOException: Failed to connect to <CLUSTERNAME>:22

and unable to connect to the cluster.
I'm using maverick jar version 3.6 -maverick-synergy-client-3.0.6-all.jar 
Kindly refer the screenshot attached. Can someone help what needs to be done? 
![cluster-authentication-failed](https://user-images.githubusercontent.com/52831765/202168144-ce6d0583-b53f-47ed-936a-9c7ecf2b6159.png)

Thanks and Regards,
Radhesh

**Comment by radhesh-kunnath** [comment]
Just an update to the above query
Used latest maverick jar 3.0.9

When i do ssh into the cluster using putty and upon checking auth.log, i have found this 
-> no matching key exchange method found . Their offer: curve25519-sha256,curve25519-sha256@libssh.org [preauth]

and when i view the ssh settings of the cluster this is what i found.
Kex Algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256

can someone help what needs to be done?

Thanks and Regards,
Radhesh.

**Comment by ludup** [comment]
Can you provide a log please?

Create logging.properties in your working directory and add
```
maverick.log.file=true
maverick.log.file.level=DEBUG
```
Then post the synergy.log file.

**Comment by radhesh-kunnath** [comment]
Hi David, 
Please find the attached. 

Thanks and Regards,
Radhesh.
[synergy.log](https://github.com/sshtools/maverick-synergy/files/10142627/synergy.log)

**Comment by radhesh-kunnath** [comment]
@ludup  I feel like based on the exception in the logs, is the cluster looking for specific ciphers in the key exchange negotiation? 
java.io.IOException: Failed to negotiate a transport component from curve25519-sha256,curve25519-sha256@libssh.org and ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256

Would love to know the root cause , any help is much appreciated asap.

**Comment by ludup** [comment]
It cannot negotiate a key exchange, but the API supports all of those key exchanges.

The problem is clear earlier in the log "JCE cannot authenticate the provider BC"

Have you tried to extract everything into a uber jar file? You cannot do that with BC, if not, there is still some error with the BC dependency.

**Comment by radhesh-kunnath** [comment]
Thanks Ludup, upon checking my working directory I have found 2 different versions of bc*.jar. Removed one of them it has fixed the issue. Thanks again @ludup .
