### ISSUE TITLE
impossible to stop background thread

### ISSUE THREAD

**Issue by gcottenc** [sshtools/maverick-synergy#6]
after invoking
`Log.getDefaultContext().enableConsole( Level.DEBUG );`
when stopping tomcat, infamous message appears:

`18-Aug-2020 17:06:17.482 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [bla] appears to have started a thread named [Thread-5] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.7/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@11.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
 java.base@11.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
 java.base@11.0.7/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
 java.base@11.0.7/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
 java.base@11.0.7/sun.nio.fs.AbstractWatchService.poll(AbstractWatchService.java:108)
 com.sshtools.common.logger.DefaultLoggerContext$FileWatcher.run(DefaultLoggerContext.java:227)
`

but also: 

`[FileSystemWatchService] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@11.0.7/sun.nio.fs.LinuxWatchService.poll(Native Method)
 java.base@11.0.7/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:316)
 java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
`

It seems that `./sources/maverick-base/src/main/java/com/sshtools/common/logger/DefaultLoggerContext.java` starts a `FileWatcher extends Thread` thread, that itself starts a WatchService which starts actually another underlying thread. There seems no API to stop them. Maybe a simple:

`	public synchronized void shutdown() {
            watcher.stopThread();
	}
`

would suffice for the created thread, and improve `stopThread` to call `close` on the underlying `watcher` WatchService object (maybe using two different local names not `watcher` twice for different objects would also be better).

**Comment by ludup** [comment]
Thanks for the report. 

As requested a new shutdown method has been added to the RootLoggingContext. 

`Log.getDefaultContext().shutdown();`

I have also added a runtime shutdown hook in the file watcher, although from my own use of Tomcat it appears this is not sufficient, most likely because in my own server the logging context is not initialized until Tomcat has started, and therefore its shutdown hook is executed after Tomcat's which I assume is where they report the potential issue. 

Either way, the API will now shut it down on exit and provides the option for doing so earlier if required.

**Comment by gcottenc** [comment]
Thanks! I updated the 3.0.0. snapshot jars to give it a try, but now your Log class disappeared, however your doc https://www.jadaptive.com/app/manpage/en/article/1564873 still refers to it. Can you please update the documentation accordingly?
