### ISSUE TITLE
"SSHD-TRANSFER-1" java.lang.StackOverflowError

### ISSUE THREAD

**Issue by SNaatanen** [sshtools/maverick-synergy#62]
MODULE:
This issue was discovered when implementing SFTP server using maverick-synergy-server API with maverick-virtual-filesystem.

ISSUE:
If you use get to transfer the servers own log file and have connection logging on the file transfer will eventually throw StackOverFlowError that has following cycle in stack (Bottom to top is the call order).
at com.sshtools.common.logger.FileLoggingContext.logToFile(FileLoggingContext.java:84)
at com.sshtools.common.logger.FileLoggingContext.log(FileLoggingContext.java:79)
at com.sshtools.common.logger.FileLoggingContext.createLogFile(FileLoggingContext.java:68)
at com.sshtools.common.logger.FileLoggingContext.checkRollingLog(FileLoggingContext.java:109)
at com.sshtools.common.logger.FileLoggingContext.logToFile(FileLoggingContext.java:84)

This can happen even if you don't have connection logging on but then it doesn't happen every time.

There are at least these issues:
1. The log rotate fails because the file is the file we are transferring.
2. The transfer hangs in client side waiting data that will never arrive because the transfer thread dies.
3. The transfer tries to send the ever growing file completely but it fails because the file grows faster than it can be sent.

My initial reasoning is that because the log rotate can never rename the original log file because it is locked for transfer.
When it thinks log rotate is done it tries to do the initial logging at the very beginning of the new log file telling the file it now logs on to.
But because the log rename fails (This is not checked btw) this initial logging is actually tried on the old log file.
It does log rotate check and sees that the file is bigger than maximum size so it tries to log rotate... and here we go in the merry go round until we run out of stack space.

STEPS TO REPRODUCE:
Create SFTP server so that you set the logging settings as follows:
1. Set the server log file path to be inside the SFTP servers virtual file system.
2. Put connection logging level to TRACE.
3. Connect to this server and use 'get' to download the server logfile.

**Comment by ludup** [comment]
Added error generation when rename or delete fails in 3.1.0-SNAPSHOT (develop) branch.
