### ISSUE TITLE
Are there javadocs?

### ISSUE THREAD

**Issue by wedgef5** [sshtools/maverick-synergy#71]
I've looked all over for javadocs, and I can't find any. Do they exist?

Also, the README has a link to community forums, but I get a 503 error when I hit the link. Are the forums going to be back?

**Comment by ludup** [comment]
It looks like they have not been uploading. 

The hotfix branch (a couple of versions on from the open-source) should be close enough and are at https://maverick-synergy-javadocs.s3.eu-west-1.amazonaws.com/index.html

But I will get the upload fixed and link from the page on our web site.

Regarding the forums... nobody came, it seems Github is enough.
