### ISSUE TITLE
SSH Client Put File Throws No connection or client supplied.

### ISSUE THREAD

**Issue by cpmoore** [sshtools/maverick-synergy#84]
Hi ya,
The ssh client command throws an IllegalArgumentException due to the following line

https://github.com/sshtools/maverick-synergy/blob/d6afd03d11d338f42cc3054803a9e61fd558e3c8/maverick-synergy-client/src/main/java/com/sshtools/client/tasks/AbstractConnectionTask.java#L84

The orElse is evaluated before returning the connection, which in turn gets evaluated to the orElseThrow since clientSupplier is empty
It needs to be converted to an orElseGet like 
``` 
super(builder.connection.orElseGet(() -> builder.clientSupplier.orElseThrow(() -> new IllegalArgumentException("No connection or client supplied.")).apply(0).getConnection()));

```

**Comment by amcarthur** [comment]
Any idea when 3.1.2 will be released? Either I'm too dumb to properly add the sonatype snapshot repo to my gradle config, or my company disabled snapshots somehow

**Comment by laurentiustroia** [comment]
Hi guys, this issue is for any usage of putFile call ? I follow this example https://jadaptive.com/java-ssh-library/ssh-client-quick-start/ but I got `java.lang.IllegalArgumentException: No connection or client supplied.` on `ssh.putFile` request

**Comment by ludup** [comment]
3.1.2 uploaded to github releases, it is also in Maven Central. Closing.
