### ISSUE TITLE
SshClientBuilder.create() fails with java.IOException

### ISSUE THREAD

**Issue by rgl-1976** [sshtools/maverick-synergy#95]
My attempt to create an SshClient with maverick-synergy-client-3.1.1-all.jar fails with:

java.io.IOException: Failed to connect to 192.168.7.161:22 
               at com.sshtools.client.SshClient.doConnect(SshClient.java:1030) 
               at com.sshtools.client.SshClient.<init>(SshClient.java:560) 
               at com.sshtools.client.SshClient$SshClientBuilder.build(SshClient.java:538) 

I am trying to generate debug output with:

import com.sshtools.common.logger.Log;
.
.
.
Log.getDefaultContext().enableConsole(Level.DEBUG); 

I'm getting an error "Cannot find symbol" for Level.DEBUG.

Any help would be appreciated.

**Comment by ludup** [comment]
The API requires maverick-logging.jar and any other dependencies. If your adding jars directly, maybe start with all jars in the download rather than a selective few to prevent this error. You can always refine the classpath later.
