### ISSUE TITLE
NPE when working directory is directly under root

### ISSUE THREAD

**Issue by abroekhuis** [sshtools/maverick-synergy#97]
When running an application from the root ("/"), a NPE is thrown by the FileWatchingService.

Looking at the code I see the following:

https://github.com/sshtools/maverick-synergy/blob/ef732b22e25188b2a3fbe0f463e46a6c65e8f42b/maverick-logging/src/main/java/com/sshtools/common/logger/DefaultLoggerContext.java#L54

In here a default "logging.properties" file is made, which has an absolute path of /logging.properties

https://github.com/sshtools/maverick-synergy/blob/ef732b22e25188b2a3fbe0f463e46a6c65e8f42b/maverick-logging/src/main/java/com/sshtools/common/logger/DefaultLoggerContext.java#L60

Next on line 60/61, that File is turned into a Path and the parent is retrieved, this results in "/".

https://github.com/sshtools/maverick-synergy/blob/ef732b22e25188b2a3fbe0f463e46a6c65e8f42b/maverick-logging/src/main/java/com/sshtools/common/logger/FileWatchingService.java#L76

Finally, in FileWatchingService, again the parent is retrieved, however, since the path is already the root, a NPE is thrown.

Looking at the logic, I think a null check is needed at those places. Also, since the file watcher gets the parent, is the call in the DefaultLoggerContext needed?

**Comment by ludup** [comment]
I don't think a null check is needed if the DefaultLoggerContext passes the propertiesPath and not its parent. 

Fixed in 3.2.0-SNAPSHOT in the develop branch.
